theme: minima
title: Lynne's blog
author: Lynne Ratcliffe
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning all about Git and creating stuff

# social links
twitter_username: Do-Not-Use-Twitter # DO NOT include the @ character, or else the build will fail!
github_username:  LZRatcliffe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
